title: Andy Liu
description: 个人主页
author: Andy Liu
logo: /static/img/avatar.png
github: https://github.com/Freeway1979
about: 混迹于移动互联网

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: 
google_analytics: 

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
